dist: trusty
sudo: false
language: java
jdk:
  - openjdk8

git:
  depth: 1

branches:
  only:
  - master

cache:
  directories:
  - "$HOME/.cache"

services:
  - docker
  - mysql
  - postgresql

addons:
  hosts:
    - mysql
    - pgsql
    - mongo

install: true

before_install:
  - openssl aes-256-cbc -K $encrypted_85e093d3bccc_key -iv $encrypted_85e093d3bccc_iv -in secret-keys.gpg.enc -out secret-keys.gpg -d
  - gpg --import secret-keys.gpg

before_script:
  - sleep 10
  - mysql -uroot -e "create database ptest;"
  - mysql -uroot -e "CREATE USER 'panda'@'127.0.0.1' IDENTIFIED BY 'panda';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON ptest.* TO 'panda'@'127.0.0.1';"
  - psql -U postgres -c "CREATE USER panda PASSWORD 'panda';"
  - psql -U postgres -c "CREATE DATABASE ptest WITH OWNER = panda ENCODING = 'UTF-8';"
  - psql -U postgres -c "GRANT ALL ON DATABASE ptest TO panda;"

script: 
  - mvn -B -s .travis.settings.xml -Dgpg.skip=false clean source:jar javadoc:jar gpg:sign cobertura:cobertura deploy

after_success:
  - bash <(curl -s https://codecov.io/bash)

